// The shell's contract (2026-09-08): the chrome moved into a top bar and a rail, and every hook the
// scripts use is still where they look for it.
'use strict';
const fs = require('fs'), path = require('path');
const { makeDocument } = require(path.join(__dirname, 'minidom.js'));
const html = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'templates', 'index.html'), 'utf8');
const results = []; const check = (n, c, d) => results.push([n, !!c, d]);
function fragment(id) { const s = html.indexOf(`id="${id}"`); const start = html.lastIndexOf('<div', s); let depth = 0; const re = /<\/?div\b[^>]*>/g; re.lastIndex = start; let m;
  while ((m = re.exec(html))) { if (m[0].startsWith('</')) { depth--; if (depth === 0) return html.slice(start, m.index + m[0].length); } else if (!m[0].endsWith('/>')) depth++; } return html.slice(start); }
const doc = makeDocument(); const root = doc.createElement('div'); root.innerHTML = html.slice(html.indexOf('<div class="container">'), html.indexOf('<div class="menu-popup">'));
check('shell: the top bar carries the wordmark (no logo shown), the dataset chips, the chain navigation, the executor status, the account and the settings menu', root.querySelector('.topbar .brand-name') && root.querySelector('.topbar .menu-logo').getAttribute('style').includes('display:none') && root.querySelector('.topbar #datasetStatusPillsContainer') && root.querySelector('.topbar .tab-navigation #prevResponse') && root.querySelector('.topbar #chainPosition') && root.querySelector('.topbar #containerStatus #containerStatusText') && root.querySelector('.topbar #authContainer') && root.querySelector('.rail .settings-container .settings-popup #themeToggle') && !root.querySelector('.topbar .settings-container'));
check('shell: the rail carries New workflow at the top, then the three pills and the map button (the scripts bind clicks to them)', root.querySelector('.rail #railNewButton') && !root.querySelector('.rail #menuButton') && root.querySelector('.rail #workflowManagerPill') && root.querySelector('.rail #datasetManagerPill') && root.querySelector('.rail #memoryReviewPill #memoryReviewBadge') && root.querySelector('.rail #railMapButton') && root.querySelector('.rail').elements[0].id === 'railNewButton');
check('shell: the panes wrapper holds the rail, the collapse handle and both panels', root.querySelector('.panes .rail') && root.querySelector('.panes #collapseButton') && root.querySelector('.panes #leftPanel') && root.querySelector('.panes #rightPanel'));
check('shell: the old menu bar is gone from the left pane', !root.querySelector('.left-panel .top-panel') && !root.querySelector('.menu-container'));
check('shell: the history drawer is gone from the page', !html.includes('class="menu-popup"') && !html.includes('id="labelsList"'));
check('shell: shell.css is linked after dialogs.css', html.indexOf("css/shell.css") > html.indexOf("css/dialogs.css"));
const shell = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'css', 'shell.css'), 'utf8');
check('shell.css: no drawer rules remain', !shell.includes('.menu-popup'));
// ---- the composer ----
const comp = root.querySelector('.input-area');
check('composer: every id the scripts address is present (input, upload, files, mode switch + popup + params, ideas, submit); Save has left it',
  ['queryInput', 'uploadButton', 'primaryFile', 'auxiliaryFile', 'modeSwitch', 'modeSliderPopup', 'modeParams', 'iterationsValue', 'suggestQuestions', 'branchingSliderPopup', 'submitQuery', 'uploadLimitMessage'].every(id => comp.querySelector('#' + id)) && !comp.querySelector('#rankButton'));
check('composer: the three mode options and the send button\'s three icons are still there for setMode() and setQueryRunning()',
  comp.querySelectorAll('#modeSliderPopup .mode-option').length === 3 && ['airplane-icon', 'globe-icon', 'stop-icon'].every(c => comp.querySelector('#submitQuery .' + c)));
check('composer: no hint line, no chips inside it (they moved to the bar)', !comp.querySelector('.composer-hint') && !comp.querySelector('#datasetStatusPillsContainer'));
check('shell.css: the mode popup is shown inline as a segmented control (the script\'s hover show/hide is inert)', shell.includes('#modeSliderPopup { display: inline-flex !important'));
check('right pane: the header row is retired; the tab container is the strip; the answer page and the provenance footer are styled', !root.querySelector('.right-panel .panel-header') && root.querySelector('.right-panel #tabContainer') && shell.includes('.right-panel .tab.active') && shell.includes('#content-answer .answer-provenance'));
const cr = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'content-rendering.js'), 'utf8'); const uc = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'ui-controls.js'), 'utf8');
check('scripts: the Data and Plots tab labels; the chain position text', cr.includes("tabName = 'Data'") && cr.includes("tabName = 'Plots'") && uc.includes("'chain ' + (currentResponseIndex + 1) + ' of '"));
// ---- v41: the five things seen on the box ----
check('top bar: the executor status holds only its icon and text (the account and the gear are its siblings, not its children)', (() => { const st = root.querySelector('.topbar #containerStatus'); return st.elements.length === 2 && !st.querySelector('.settings-container') && !st.querySelector('#authContainer'); })());
check('shell.css: the collapse handle sits flush on the divider (rail + 12) and clears the rail when collapsed', shell.includes('.panes .collapse-button { margin-left: 58px; }') && shell.includes('.panes:has(.left-panel.collapsed) .collapse-button { margin-left: 46px; }'));
check('shell.css: the attach menu has no gap and a bridge, so the hover survives the move into it', shell.includes('.left-panel .attach-menu { position: absolute; bottom: 100%;') && shell.includes('.left-panel .attach-menu::before { content: \'\'; display: block; position: absolute; left: 0; right: 0; bottom: -10px;'));


check('ui-controls.js: the menu toggle is a no-op without the drawer', uc.includes("if (!document.querySelector('.menu-popup')) return;"));
// ---- v42 ----
check('rail: the gear sits at the bottom of the rail with its menu opening to the right, on hover or click, bridged', root.querySelector('.rail .rail-gap') && shell.includes('.rail .settings-popup { position: absolute; left: 100%; bottom: 0;') && shell.includes('.rail .settings-container:hover .settings-popup, .rail .settings-container:focus-within .settings-popup { display: flex; }'));
check('top bar: the executor status is a dot and a word, coloured by state', shell.includes('.topbar .container-status::before') && shell.includes('.topbar .container-status.status-ready, .topbar .container-status.status-online { color: var(--c-model)'));
check('ui-controls.js: the ideas popover is anchored to its button when shown', uc.includes("branchingSliderPopup.style.left = suggestQuestions.offsetLeft + 'px'"));
check('top bar: a chip\'s remove icon inherits the chip\'s colour', shell.includes('.topbar .dataset-status-pill .dataset-pill-remove-icon { color: inherit;'));
check('answer tab: the Simplified/Technical toggle and the PDF button are styled as small buttons on one toolbar line', shell.includes('#content-answer .simplified-summary-btn, #content-answer .pdf-export-btn {') && shell.includes('#content-answer .tab-header-container h3 { display: none; }'));
// ---- v43 ----
check('shell.css: a collapsed left pane really collapses (the right pane takes the width)', shell.includes('.container .left-panel.collapsed { flex: 0 0 0; width: 0;'));
check('shell.css: a chip\'s remove icon strokes in the chip\'s colour at the old rules\' theme-level specificity', shell.includes('[data-theme="dark"] .topbar .dataset-status-pill.auxiliary-dataset-pill.success .dataset-pill-remove-icon svg') && shell.includes('.dataset-pill-remove-icon svg { stroke: currentColor; fill: none; }'));
check('answer page: the toolbar is pinned to the top-right corner with the content\'s margins; the key figure and citation chips are styled', shell.includes('#content-answer .tab-header-container { position: absolute; top: 18px; right: 24px;') && shell.includes('#content-answer .answer-key {') && shell.includes('#content-answer .cite {'));
const sp = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'stream-pane.js'), 'utf8');
check('stream-pane.js: the closing card writes the best estimate as the answer\'s key figure and turns [cell n]/[fig n] into chips', sp.includes("key.className = 'answer-key'") && sp.includes("class=\"cite ' + kind + '\""));
// ---- v44: the fold ----
const cssdir = path.join(__dirname, '..', '..', 'web_app', 'static', 'css');
check('fold: pane.css and tabs.css are linked after shell.css and hold the pane, grid and notebook blocks', html.indexOf("css/pane.css") > html.indexOf("css/shell.css") && html.indexOf("css/tabs.css") > html.indexOf("css/pane.css") && fs.readFileSync(path.join(cssdir, 'pane.css'), 'utf8').includes('.sp-strip') && fs.readFileSync(path.join(cssdir, 'tabs.css'), 'utf8').includes('.nb-cell') && fs.readFileSync(path.join(cssdir, 'tabs.css'), 'utf8').includes('.dg '));
check('fold: styles.css no longer carries the pane, grid or notebook blocks, nor the retired rules', (() => { const s = fs.readFileSync(path.join(cssdir, 'styles.css'), 'utf8'); return !s.includes('.sp-strip') && !s.includes('.nb-cell') && !s.includes('.top-panel {') && !s.includes('.scroll-indicator') && !s.includes('.yaml-wrapper'); })());
check('fold: the scroll indicator is gone from the page; api-keys.css is retired', !html.includes('scroll-indicator') && !html.includes("css/api-keys.css"));
check('fold: the retired archive is not linked; the legacy sheet carries the old Plan/YAML rules', !html.includes('_retired.css') && fs.readFileSync(path.join(cssdir, 'tool-call-styles.css'), 'utf8').includes('.yaml-wrapper'));
// ---- v45: the Code, Results and Plots tabs; the answer's type size; the send button ----
const tabsCss = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'css', 'tabs.css'), 'utf8');
check('tabs.css: Code and Results are one code block with the toolbar; Plots are cards with a header, query row and figure', tabsCss.includes('#content-code .code-header {') && tabsCss.includes('#content-code pre code, #content-code_exec_results pre code {') && tabsCss.includes('#content-plot .plot-container {') && tabsCss.includes('#content-plot .plot-query-form {'));
check('tabs.css: the answer page reads at 14.5px', tabsCss.includes('#content-answer .markdown-content { font-size: 14.5px;'));
check('shell.css: the send button is a small filled square at id-level specificity (the old #submitQuery rule no longer wins)', shell.includes('.left-panel #submitQuery { position: absolute; right: 8px; bottom: 8px;') && shell.includes('width: 24px; height: 24px; margin: 0; padding: 0; border-radius: 6px; border: none; background: var(--c-model)'));
// ---- v46: the thread map as a drawer ----
const mroot = doc.createElement('div'); mroot.innerHTML = fragment('workflowMapModal');
check('map drawer: every id the scripts address is in place (container, details, preview, the two actions, the close)', ['workflowMapContainer', 'workflowDetailsPane', 'nodeTaskContent', 'nodePlotPreview', 'trajectoryButton', 'synthesisButton', 'mapDrawerSub'].every(id => mroot.querySelector('#' + id)) && mroot.querySelector('.workflow-close') && mroot.querySelector('#workflowMapModal').className.includes('map-drawer'));
check('rail: its own initialiser binds New workflow (handleNewConversation) and the map; the menu code is inert without the drawer', uc.includes('function initializeRail()') && uc.includes("railNewButton.addEventListener('click'") && uc.includes('handleNewConversation();') && uc.includes("if (!document.querySelector('.menu-popup')) return;"));
const wg = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'workflowGraph.js'), 'utf8'); const wm = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'workflow-management.js'), 'utf8');
check('workflowGraph.js: a node click navigates and closes the drawer; the controls sit on the frame, the graph fits it, hover shows the chain\'s basics; workflow-management.js writes the subtitle', wg.includes("if (drawer) drawer.style.display = 'none'") && wg.includes('var controlsHost = mapContainer.parentElement') && wg.includes('function fitToFrame(') && wg.includes("class=\"wf-info-row\"") && !wg.includes('renderPlotlyPreview(plotData)') && wm.includes("document.getElementById('mapDrawerSub')"));
check('shell.css: zoom at the frame\'s top-left, expand at its top-right; the hover basics styled', shell.includes('#workflowMapModal .wf-zoom-controls { position: absolute; left: 10px; top: 10px;') && shell.includes('#workflowMapModal .wf-fullscreen-btn { position: absolute; right: 10px; top: 10px;') && shell.includes('#workflowMapModal .wf-info {'));
check('shell.css: the drawer, the graph and its controls are styled; workflow-map.css is retired (its variation pills kept)', shell.includes('#workflowMapModal.map-drawer {') && shell.includes('#workflowMapModal .wf-node--active') && shell.includes('.variation-pill') && !html.includes("css/workflow-map.css"));
// ---- v48: the Explore page ----
const qp = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'query-processing.js'), 'utf8'); const core = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'core.js'), 'utf8');
check('explore: an answer flagged explore becomes the Explore tab (interactive cards) and gets no PDF or Simplified buttons', qp.includes("if (data.type === 'answer' && data.explore) { answerTabInteractive = true; answerTabExplore = true; }") && core.includes('let answerTabExplore = false;') && cr.includes("!(typeof answerTabExplore !== 'undefined' && answerTabExplore)") && cr.includes("tab.textContent = answerTabInteractive ? 'Explore'"));
check('tabs.css: the Explore cards are styled (number, title, question, edit, run)', tabsCss.includes('#content-answer .interactive-pill {') && tabsCss.includes('#content-answer .pill-edit-input {') && tabsCss.includes('#content-answer > h3 { display: none; }'));
// ---- v50 ----
const cs = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'container-status.js'), 'utf8');
check('executor chip: a cell_start event turns it to Executing and a cell end or run end turns it back', qp.includes('data.type === "pane_cell_start"') && qp.includes("setExecuting(true)") && qp.split("setExecuting(false)").length >= 3 && cs.includes("el.className = 'container-status status-execution'"));
const dcss2 = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'css', 'dialogs.css'), 'utf8');
check('loader dialogs: the chips centre their text (the check takes no room until chosen) and the Load button is a labelled button', dcss2.includes('.integration-dialog .int-options label { display: inline-flex; align-items: center; justify-content: center;') && dcss2.includes('.integration-dialog .circular-button { width: auto; height: 30px;'));
// ---- v51 ----
check('top bar: a dataset from Intervals, SweatStack or Endura is the primary and wears the model green', shell.includes('.topbar .dataset-status-pill.intervals-dataset-pill, .topbar .dataset-status-pill.sweatstack-dataset-pill, .topbar .dataset-status-pill.endura-dataset-pill { border-color: var(--chip-model-border); color: var(--c-model); }'));
check('loader dialogs: the date inputs are border-box and may shrink, so the two sit side by side inside the dialog', dcss2.includes('.integration-dialog .date-input, .integration-dialog .endura-race-select { height: 32px; box-sizing: border-box; width: 100%; min-width: 0;'));
// ---- v52: the last old sheets folded; base.css; the login, the label editor, the tooltip ----
check('fold: container-status, auto-explore, graph-controls, labels and auth sheets are no longer linked; base.css is, after tokens', ['container-status.css', 'auto-explore.css', 'graph-controls.css', 'labels.css', 'auth.css'].every(f => !html.includes("css/" + f)) && html.indexOf("css/base.css") > html.indexOf("css/tokens.css") && html.indexOf("css/base.css") < html.indexOf("css/styles.css"));
check('fold: the sign-in screen, the status tooltip, the Adaptive indicator, the label editor and the diagram frame are styled in the new sheets', shell.includes('.auth-screen {') && shell.includes('.container-status-tooltip {') && shell.includes('.left-panel .auto-explore-indicator {') && dcss2.includes('#labelModal .label-modal-dialog {') && tabsCss.includes('.diagram-container {'));
check('fold: the linked stylesheets are the nine of the new set (plus the legacy sheet)', (html.match(/filename='css\//g) || []).length === 9);
check('tokens: the light theme\'s accent is dark enough for text', fs.readFileSync(path.join(cssdir, 'tokens.css'), 'utf8').includes('--accent-color: #1f9a56'));
check('status tooltip: sized to its text (no fixed minimum width)', shell.includes('.container-status-tooltip { position: fixed; z-index: 1200; width: max-content; min-width: 0; max-width: 260px;'));
// ---- v56 ----
check('pane: the heartbeat strip is flush with the pane\'s top and above the cards; the prompt buttons sit beneath it', shell.includes('.left-panel #streamOutput { padding: 0 12px 0; }') && shell.includes('.left-panel #streamOutput .sp-strip { top: 0; height: 41px; box-sizing: border-box; margin: 0 -12px 8px;') && shell.includes('z-index: 20;') && shell.includes('.left-panel #streamOutput .sp-prompt, .left-panel #streamOutput .agent-instructions-btn { z-index: 1; }'));
check('pane: the prompt button lets its click reach the document handler (preventDefault only)', sp.includes('onclick="event.preventDefault();">⌘</button>') && !sp.includes('event.stopPropagation();">⌘'));
check('rail: one tooltip per button - data-tip, no native title, no hover transform to trap it', root.querySelectorAll('.rail [title]').length === 0 && root.querySelectorAll('.rail [data-tip]').length >= 5 && shell.includes('.rail .rb[data-tip]:hover::after { content: attr(data-tip);') && shell.includes('.rail .rb, .rail .rb:hover { transform: none !important; }'));
// ---- v57 ----
check('top bar: the Save button (#rankButton, shown by the scripts when a chain finishes) sits beside the chain navigation with a bookmark and the label Save', root.querySelector('.topbar #rankButton .rank-label') && html.indexOf('id="rankButton"') > html.indexOf('id="nextResponse"') && html.indexOf('id="rankButton"') < html.indexOf('id="containerStatus"') && root.querySelector('.topbar #rankButton svg') && shell.includes('.topbar #rankButton { width: auto !important;') && shell.includes('border: 1px solid var(--border-color); border-radius: 12px; background: none; color: var(--text-secondary);') && shell.includes('.container .topbar { display: flex; align-items: center; gap: 6px;'));
check('panes: the left strip is the tab strip\'s height, so the two dividers meet', shell.includes('.left-panel #streamOutput .sp-strip { top: 0; height: 41px; box-sizing: border-box;'));
// ---- v60: the running chain while you browse ----
const wm2 = fs.readFileSync(path.join(__dirname, '..', '..', 'web_app', 'static', 'js', 'workflow-management.js'), 'utf8');
check('live chain: a running chain is a navigable entry; its DOM parks in holders while another chain is viewed; the renderer and the pane write to the live targets', wm2.includes('function beginLiveChain()') && wm2.includes('function liveGoAway()') && wm2.includes('function liveComeBack()') && wm2.includes('function liveTargets()') && qp.includes('beginLiveChain();') && qp.includes('currentData = liveState.data;') && cr.includes("_lt ? _lt.tabs : document.getElementById('tabContainer')") && sp.includes("liveTargets().stream"));
check('live chain: rebuilding a viewed chain targets the view, not the parked run', wm2.includes('liveState.forceView = true;'));
let fails = 0; for (const [n, ok, d] of results) { console.log((ok ? '  ok   ' : '  FAIL ') + n + (ok ? '' : '  <- ' + (d || ''))); if (!ok) fails++; }
console.log(`\n${results.length - fails} passed, ${fails} failed`); process.exit(fails ? 1 : 0);
